version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"  # <--- ESTO ES VITAL: Abre el puerto del backend
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"  # <--- ESTO ES VITAL: Abre el puerto del frontend
    depends_on:
      - backend